<a href="https://colab.research.google.com/github/ludmiladenise/DataScientist/blob/main/Palladino_Ludmila_Checkpoint1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Carga e Inspección:

In [2]:

# 1. Importar la biblioteca pandas
import pandas as pd

In [3]:
# 2. Cargar el dataset
df = pd.read_csv("https://raw.githubusercontent.com/ludmiladenise/DataScientist/refs/heads/main/MedicalDataset.csv")

In [4]:
# 3. Visualizar las primeras 5 filas para inspeccion visual de los registros.

display(df.head())

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No

#
Mediante la función head() se realizó una primera inspección visual de los registros, permitiendo identificar las columnas y observar la estructura inicial de la información.

In [ ]:
# 1. Dimensiones exactas del dataset
print(f"Dimensiones del dataset: {df.shape} ")

Dimensiones del dataset: (110527, 14)

Con el atributo shape, se determinó que el dataset contiene cantidad de filas 110527 registros y cantidad de columnas 14 columnas.

# Perfilado Inicial:

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PatientId       110527 non-null  float64
 1   AppointmentID   110527 non-null  int64
 2   Gender          110527 non-null  object
 3   ScheduledDay    110527 non-null  object
 4   AppointmentDay  110527 non-null  object
 5   Age             110527 non-null  int64
 6   Neighbourhood   110527 non-null  object
 7   Scholarship     110527 non-null  int64
 8   Hipertension    110527 non-null  int64
 9   Diabetes        110527 non-null  int64
 10  Alcoholism      110527 non-null  int64
 11  Handcap         110527 non-null  int64
 12  SMS_received    110527 non-null  int64
 13  No-show         110527 non-null  object
dtypes: float64(1), int64(8), object(5)
memory usage: 11.8+ MB

Mediante el método info(), se analizaron los tipos de datos de cada variable y la cantidad de valores no nulos, con el objetivo de identificar posibles necesidades de limpieza y preparación de los datos antes de continuar con el análisis exploratorio.

In [ ]:
#Calcular valores nulos por columna.
print("Valores nulos por columna:")
print(df.isnull().sum())

Valores nulos por columna:
PatientId         0
AppointmentID     0
Gender            0
ScheduledDay      0
AppointmentDay    0
Age               0
Neighbourhood     0
Scholarship       0
Hipertension      0
Diabetes          0
Alcoholism        0
Handcap           0
SMS_received      0
No-show           0
dtype: int64

Se realizó un perfilado inicial del conjunto de datos mediante Pandas. En primer lugar, se calcularon los valores nulos por columna utilizando isnull().sum(), con el propósito de identificar variables con información faltante.

In [ ]:
#Obtener estadísticas descrptivas
print("\nEstadísticas descriptivas:")
display(df.describe())

Estadísticas descriptivas:

,PatientId,AppointmentID,Age,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received
count,1.105270e+05,1.105270e+05,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000
mean,1.474963e+14,5.675305e+06,37.088874,0.098266,0.197246,0.071865,0.030400,0.022248,0.321026
std,2.560949e+14,7.129575e+04,23.110205,0.297675,0.397921,0.258265,0.171686,0.161543,0.466873
min,3.921784e+04,5.030230e+06,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.172614e+12,5.640286e+06,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3.173184e+13,5.680573e+06,37.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,9.439172e+13,5.725524e+06,55.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,9.999816e+14,5.790484e+06,115.000000,1.000000,1.000000,1.000000,1.000000,4.000000,1.000000


Se aplicó el método describe() para obtener estadísticas descriptivas de las variables numéricas, incluyendo medidas de tendencia central, dispersión y valores mínimos y máximos.

In [ ]:
display(df.describe(include='all'))

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
count,1.105270e+05,1.105270e+05,110527,110527,110527,110527.000000,110527,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000,110527
unique,NaN,NaN,2,103549,27,NaN,81,NaN,NaN,NaN,NaN,NaN,NaN,2
top,NaN,NaN,F,2016-05-06T07:09:54Z,2016-06-06T00:00:00Z,NaN,JARDIM CAMBURI,NaN,NaN,NaN,NaN,NaN,NaN,No
freq,NaN,NaN,71840,24,4692,NaN,7717,NaN,NaN,NaN,NaN,NaN,NaN,88208
mean,1.474963e+14,5.675305e+06,NaN,NaN,NaN,37.088874,NaN,0.098266,0.197246,0.071865,0.030400,0.022248,0.321026,NaN
std,2.560949e+14,7.129575e+04,NaN,NaN,NaN,23.110205,NaN,0.297675,0.397921,0.258265,0.171686,0.161543,0.466873,NaN
min,3.921784e+04,5.030230e+06,NaN,NaN,NaN,-1.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
25%,4.172614e+12,5.640286e+06,NaN,NaN,NaN,18.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
50%,3.173184e+13,5.680573e+06,NaN,NaN,NaN,37.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
75%,9.439172e+13,5.725524e+06,NaN,NaN,NaN,55.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,NaN
max,9.999816e+14,5.790484e+06,NaN,NaN,NaN,115.000000,NaN,1.000000,1.000000,1.000000,1.000000,4.000000,1.000000,NaN

In [ ]:

print("Hipertensión:",
      round(df['Hipertension'].mean() * 100, 2), "%")

print("Diabetes:",
      round(df['Diabetes'].mean() * 100, 2), "%")

print("Mensaje SMS:",
      round(df['SMS_received'].mean() * 100, 2), "%")

print("No-show (Asistieron):", round((df['No-show'] == 'No').mean() * 100, 2), "%")

Hipertensión: 19.72 %
Diabetes: 7.19 %
Mensaje SMS: 32.1 %
No-show (Asistieron): 79.81 %

Se utilizó describe(include='all') para ampliar el análisis a las variables categóricas.

El conjunto de datos está compuesto por 110.527 registros y 14 variables relacionadas con turnos médicos, características de los pacientes y asistencia a las consultas.

A través de las estadísticas descriptivas se identificó que la edad promedio de los pacientes es de 37,09 años, con una mediana de 37 años. La categoría de género más frecuente es el Femenino. El vecindario con mayor cantidad de registros es Jardim Camburi, con 7.717 observaciones.

En relación con las variables de salud, se observa que el 19,72 % de los registros presenta hipertensión y el 7,19 % diabetes. Asimismo, aproximadamente el 32,10 % de los turnos registra la recepción de un mensaje SMS. La categoría predominante de la variable No-show es No, que representa el 79,81 % de los registros.

Durante la inspección también se identificaron valores que requieren revisión, como una edad mínima de -1 y un valor máximo de 4 en la variable Handcap.

# Saneamiento y Selección.

Pregunta de investigacion:
¿Qué factores demográficos, de salud y de comunicación se relacionan con la inasistencia a los turnos médicos?

In [ ]:

# Primero Filtramos pacientes con edades entre 0 y 100 años.
df_filtrado = df[(df['Age'] >= 0) & (df['Age'] <= 100)]

In [ ]:
# Verificar las dimensiones del nuevo dataset
print("Dimensiones originales:", df.shape)
print("Dimensiones filtradas:", df_filtrado.shape)

Dimensiones originales: (110527, 14)
Dimensiones filtradas: (110519, 14)

In [ ]:
# Mostrar las primeras filas
display(df_filtrado.head())

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No

¿Qué hace este código?
- df['Age'] >= 0: selecciona registros con edades iguales o mayores a cero.
- df['Age'] <= 100: selecciona registros con edades de hasta 100 años.
- &: combina ambas condiciones; tienen que cumplirse las dos.

El resultado se guarda en df_filtrado, por lo que conservás el dataset original en df.

In [ ]:
# Seleccionar pacientes adultos que no asistieron
df_inasistencias = df_filtrado[
    (df_filtrado['Age'] >= 18) &
    (df_filtrado['No-show'] == 'Yes')
]

In [ ]:
# Mostrar resultados
display(df_inasistencias.head())

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
6,7.336882e+14,5630279,F,2016-04-27T15:05:12Z,2016-04-29T00:00:00Z,23,GOIABEIRAS,0,0,0,0,0,0,Yes
7,3.449833e+12,5630575,F,2016-04-27T15:39:58Z,2016-04-29T00:00:00Z,39,GOIABEIRAS,0,0,0,0,0,0,Yes
11,7.542951e+12,5620163,M,2016-04-26T08:44:12Z,2016-04-29T00:00:00Z,29,NOVA PALESTINA,0,0,0,0,0,1,Yes
17,1.479497e+13,5633460,F,2016-04-28T09:28:57Z,2016-04-29T00:00:00Z,40,CONQUISTA,1,0,0,0,0,0,Yes
20,6.222575e+14,5626083,F,2016-04-27T07:51:14Z,2016-04-29T00:00:00Z,30,NOVA PALESTINA,0,0,0,0,0,0,Yes

In [ ]:
print("Total de turnos de adultos con inasistencia:",
      df_inasistencias.shape[0])

Total de turnos de adultos con inasistencia: 16319

En este dataset, No-show == 'Yes' indica que el paciente no asistió al turno, mientras que No-show == 'No' indica que sí asistió.

**Eliminar columnas innecesarias.**

Para analizar los factores asociados a la asistencia, los identificadores individuales (id)  no suelen aportar información explicativa directa. Al eliminarlos conservarmos las variables relevantes.

In [ ]:

# Eliminar columnas identificadoras
df_analisis = df_filtrado.drop(
    columns=['PatientId', 'AppointmentID']
)

In [ ]:
# Verificar el resultado
print("Dimensiones del dataset seleccionado:", df_analisis.shape)

display(df_analisis.head())

Dimensiones del dataset seleccionado: (110519, 12)

,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No

Se aplicaron filtros booleanos para realizar una limpieza del conjunto de datos y obtener subconjuntos relevantes para la investigación sobre los factores asociados a la inasistencia a turnos médicos.

En primer lugar, se filtraron los registros para conservar pacientes con edades entre 0 a 100 años, con el objetivo de excluir valores fuera del rango definido para el análisis. Posteriormente, se creó un subconjunto de pacientes adultos que no asistieron a sus turnos, utilizando las variables Age y No-show.

Además, se eliminaron las columnas PatientId y AppointmentID, dado que funcionan como identificadores y no aportan información explicativa.
Se conservaron las variables demográficas, de salud, ubicación, programación de turnos y recepción de mensajes, junto con No-show como variable objetivo.

Estas operaciones permiten organizar los datos y concentrar el análisis en las variables que podrían estar relacionadas con la asistencia o inasistencia de los pacientes.